# @format

version: '3.9' # optional since v1.27.0
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    entrypoint: './init.sh'

  db:
    image: postgres:14.7
    ports:
      - 5432:5432
    env_file:
      - .env.dev
