jdbc {
  dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
  dataSource.user = "user"
  dataSource.user = ${?POSTGRES_USER}
  dataSource.password = ""
  dataSource.password = ${?POSTGRES_PASSWORD}
  dataSource.databaseName = "languages"
  dataSource.databaseName = ${?POSTGRES_DB}
  dataSource.portNumber = 5432
  dataSource.portNumber = ${?POSTGRES_PORT}
  dataSource.serverName = "127.0.0.1"
  dataSource.serverName = ${?POSTGRES_HOST}
  connectionTimeout = 30000
}

http {
    interface = "localhost"
    port = 8080
}